In [1]:
from funcoesTermosol import *
import pandas as pd
import numpy as np

In [2]:
[nn,N,nm,Inc,nc,F,nr,R] = importa('entrada.xls')
dados = [nn,N,nm,Inc,nc,F,nr,R] 
dados

[3,
 array([[0. , 0. , 0.3],
        [0. , 0.4, 0.4]]),
 3,
 array([[1.0e+00, 2.0e+00, 2.1e+11, 2.0e-04],
        [2.0e+00, 3.0e+00, 2.1e+11, 2.0e-04],
        [3.0e+00, 1.0e+00, 2.1e+11, 2.0e-04]]),
 2,
 array([[   0.],
        [   0.],
        [   0.],
        [   0.],
        [ 150.],
        [-100.]]),
 3,
 array([[0.],
        [2.],
        [3.]])]

In [6]:
print(N[0][1], N[1][1])

0.0 0.4


In [5]:
# Loop para definir as coordenadas, incidencias, forcas e restricoes de cada nó
dict_nodes = {}
for i in range(nm):
    # Calculo da matriz de rigidez para cada um dos elementos 


SyntaxError: incomplete input (982377198.py, line 11)

In [ ]:
u_force_node3 = F[4]
v_force_node3 = F[5]
print(u_force_node3, v_force_node3)

[150.] [-100.]
